### ISSUE TITLE
Price not shown

### ISSUE THREAD

**Issue by erichuang2015** [hexonet/python-sdk#2]
Hi

I am trying this api to get domain price from channels, 

```
'Command': "CheckDomains",
'DOMAIN0 ': "premium.guru",
'PREMIUMCHANNELS':"*"
```

this command runs but it does not show me the price

```
[RESPONSE]
PROPERTY[DOMAINCHECKTIME][0]=0.182
PROPERTY[PRICE][0]=
PROPERTY[PREMIUMCHANNEL][0]=
PROPERTY[REASON][0]=Domain exists
PROPERTY[CLASS][0]=PREMIUM_DONUTS_BB+
PROPERTY[CURRENCY][0]=
PROPERTY[DOMAINCHECK][0]=211 Premium Domain name not available [PREMIUM]
DESCRIPTION=Command completed successfully
CODE=200
QUEUETIME=0
RUNTIME=0.191

QUEUETIME=0
RUNTIME=0.205

EOF
```

**Comment by papakai** [comment]
Hi @erichuang2015 

Thanks for working with our SDK. Prices are only returned in case of aftermarket domains.
Reason: The price itself depends on given price by the aftermarket platform and can not calculated by using the price relations assigned to you.

In this API response you get CLASS "PREMIUM_DOMUTS_BB+" returned. That's the base to use for price estimation.

```
COMMAND = StatusUser
```
The above command returns your account balance + currency and further more the prices assigned to you. RELATIONTYPE and RELATIONVALUE are the keys and values identifying all your price.
In your case: Get all RELATIONTYPEs matching PRICE_CLASS_DOMAIN_PREMIUM_DONUTS_BB+_*

e.g.
```
PRICE_CLASS_DOMAIN_PREMIUM_DONUTS_BB+_SETUP
PRICE_CLASS_DOMAIN_PREMIUM_DONUTS_BB+_ANNUAL
PRICE_CLASS_DOMAIN_PREMIUM_DONUTS_BB+_CURRENCY
etc.

price = PRICE_CLASS_DOMAIN_PREMIUM_DONUTS_BB+_SETUP + ( x * PRICE_CLASS_DOMAIN_PREMIUM_DONUTS_BB+_ANNUAL)
```
where 'x' is the registration term. e.g. 1 = 1Y, 2 = 2Y etc.
NOTE: this just calculates the price using the currency provided in RELATIONVALUE at index of PRICE_CLASS_DOMAIN_PREMIUM_DONUTS_BB+_CURRENCY

You probably have to change it into you account currency given by status user command.

```
COMMAND = QueryDomainOptions
WIDE = 1
DOMAIN0 = premium.guru
```
Might help you to identify allowed registration periods. You can identify it under ZONEREGISTRATIONPERIODS.

We know that a library helping to calculate prices would be very helpful, this is in discussion. But actually we cannot provide you an ETA for it nor if that module will ever be realized.
But your request shows us the need for this.

Let me know if I can further support you.

Thanks so much
Kai

**Comment by erichuang2015** [comment]
Thanks Kai

Yes, I think it is great demand for price query. As you know,  new gtld hold different  price tiers  and they  vary a lot, it is good to have this lib for some pre checks.

**Comment by papakai** [comment]
No Problem, you're welcome. In general our price relation system is flexible enough. We just cannot expect a customer to know how to calculate prices as described above (and this wasn't the complete guide). Internally we already have a solution for our web platform that we provide to endcustomers and resellers. But having a solution for people who want to create their own frontend on top of our API, would also be a very good idea. This part is imo a blocker - I'll keep you posted on this topic.

Let me know if I can further support you.

Thanks so much
Kai
